path_classifiers:
  library:
    - googletest
    - radiotap
  test:
    - tests
extraction:
  cpp:
    prepare:
      # Ubuntu packages to be installed
      packages:
        - libpcap-dev
        - libev-dev
        - libnl-3-dev
        - libnl-genl-3-dev
        - libnl-route-3-dev
